### ISSUE TITLE
error invalid syntax

### ISSUE THREAD

**Issue by bnsave100** [XMYSTERlOUSX/mega-link-downloader-bot#1]
2021-08-02T04:51:11.001254+00:00 app[worker.1]:     download_directory = tmp_directory_for_each_user + "/" + fname

2021-08-02T04:51:11.001256+00:00 app[worker.1]:     ^

2021-08-02T04:51:11.001273+00:00 app[worker.1]: SyntaxError: invalid syntax

2021-08-02T04:51:11.118032+00:00 heroku[worker.1]: Process exited with status 1

2021-08-02T04:51:11.175592+00:00 heroku[worker.1]: State changed from up to crashed

2021-08-02T04:51:11.182761+00:00 heroku[worker.1]: State changed from crashed to starting

2021-08-02T04:51:20.876633+00:00 heroku[worker.1]: Starting process with command `python3 bot.py`

2021-08-02T04:51:21.658079+00:00 heroku[worker.1]: State changed from starting to up

2021-08-02T04:51:24.625573+00:00 app[worker.1]: 2021-08-02 04:51:24,625 - pyrogram.crypto.aes - INFO - Using TgCrypto

2021-08-02T04:51:24.738944+00:00 app[worker.1]: 2021-08-02 04:51:24,738 - asyncio - DEBUG - Using selector: EpollSelector

2021-08-02T04:51:26.482547+00:00 app[worker.1]: Pyrogram v1.2.9, Copyright (C) 2017-2021 Dan <https://github.com/delivrance>

2021-08-02T04:51:26.482565+00:00 app[worker.1]: Licensed under the terms of the GNU Lesser General Public License v3 or later (LGPLv3+)

2021-08-02T04:51:26.482566+00:00 app[worker.1]: 

2021-08-02T04:51:29.844440+00:00 heroku[worker.1]: Process exited with status 1

2021-08-02T04:51:29.662372+00:00 app[worker.1]: Traceback (most recent call last):

2021-08-02T04:51:29.662406+00:00 app[worker.1]:   File "/app/bot.py", line 33, in <module>

2021-08-02T04:51:29.662512+00:00 app[worker.1]:     app.run()

2021-08-02T04:51:29.662543+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/methods/utilities/run.py", line 61, in run

2021-08-02T04:51:29.662757+00:00 app[worker.1]:     self.start()

2021-08-02T04:51:29.662783+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/sync.py", line 56, in async_to_sync_wrap

2021-08-02T04:51:29.662979+00:00 app[worker.1]:     return loop.run_until_complete(coroutine)

2021-08-02T04:51:29.663007+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete

2021-08-02T04:51:29.663359+00:00 app[worker.1]:     return future.result()

2021-08-02T04:51:29.663384+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/methods/utilities/start.py", line 68, in start

2021-08-02T04:51:29.663499+00:00 app[worker.1]:     await self.initialize()

2021-08-02T04:51:29.663524+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/methods/auth/initialize.py", line 44, in initialize

2021-08-02T04:51:29.663629+00:00 app[worker.1]:     self.load_plugins()

2021-08-02T04:51:29.663652+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/client.py", line 715, in load_plugins

2021-08-02T04:51:29.663902+00:00 app[worker.1]:     module = import_module(module_path)

2021-08-02T04:51:29.663906+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/importlib/__init__.py", line 127, in import_module

2021-08-02T04:51:29.664028+00:00 app[worker.1]:     return _bootstrap._gcd_import(name[level:], package, level)

2021-08-02T04:51:29.664048+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import

2021-08-02T04:51:29.664156+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load

2021-08-02T04:51:29.664236+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked

2021-08-02T04:51:29.664315+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked

2021-08-02T04:51:29.664395+00:00 app[worker.1]:   File "<frozen importlib._bootstrap_external>", line 846, in exec_module

2021-08-02T04:51:29.664542+00:00 app[worker.1]:   File "<frozen importlib._bootstrap_external>", line 983, in get_code

2021-08-02T04:51:29.664695+00:00 app[worker.1]:   File "<frozen importlib._bootstrap_external>", line 913, in source_to_code

2021-08-02T04:51:29.664837+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed

2021-08-02T04:51:29.664985+00:00 app[worker.1]:   File "/app/plugins/megadl.py", line 156

2021-08-02T04:51:29.665011+00:00 app[worker.1]:     download_directory = tmp_directory_for_each_user + "/" + fname

2021-08-02T04:51:29.665033+00:00 app[worker.1]:     ^

2021-08-02T04:51:29.665089+00:00 app[worker.1]: SyntaxError: invalid syntax

2021-08-02T04:51:29.924874+00:00 heroku[worker.1]: State changed from up to crashed

**Comment by XMYSTERlOUSX** [comment]
@bnsave100 Sorry didn't see you here! This error has been fixed now and so many new features has been added! Please read the readme of the repo for finding what's new! Please kindly redeploy!
